import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Nav from '@/components/Navbar/Nav'
import NotionLogo from "@/public/stubsuitelogo.png";
import Book from "@/public/wikis-icon.png";
import Paper from "@/public/docs-icon.png";
import Point from "@/public/projects-icon.png";
import HomeHero from "@/public/home-hero.png";
import Desktop from "@/public/sidekick-desktop-app.png";
import Mobile from "@/public/sidekick-mobile-app.png";
import Combine from "@/public/combine.png";
import Girl from "@/public/wiki-illo.png";
import GirlSide from "@/public/engineering-wiki-V2.png";
import ToolsBeforeNotion from "@/public/tools-before-notion-V2.png";
import ToolsStrikethrough from "@/public/tools-strikethrough-V2.png";
import GiantPencil from "@/public/giant-pencil-illustration.png";
import Metalab from "@/public/metalab.png";
import TopPeekI from "@/public/topPeekI.png";
import CustomizeInfo from "@/public/customize-info.png";
import Avatars from "@/public/avatars.png";
import CommunityIcons from "@/public/community-icons-V2.png";
import WelcomeToNotion from "@/public/welcome-to-notion.png";
import NotionParade from "@/public/notion-parade.png";
import buildAnyPageCommunicateAnyIdea from "@/public/build-any-page-communicate-any-idea.png";
import MeetingNotes from "@/public/meeting-notes.png";
import Projects from "@/public/projects.png";
import AiV5 from "@/public/ai-V5.png";
import DocsIllo from "@/public/docs-illo.png";
import ProjectsIllo from "@/public/projects-illo.png";
import AiIlloV5 from "@/public/ai-illo-V5.png";
import TwitterAvatarDeborah from "@/public/twitter-avatar-deborah.png";
import CompanyWikiTemplate from "@/public/company-wiki-template.png";
import Link from 'next/link';
import LowerCarosal from '@/components/Carosal/LowerCarosal';
import UpperCarosal from '@/components/Carosal/UpperCarosal';
import SimpleCarosal from '@/components/Carosal/SimpleCarosal';
import ServicesV1 from '@/components/services/ServicesV1';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <div className="container">
        <div className="row" style={{ marginTop: '80px' }}>
          {/* display only below md */}
          <div className="col-12 d-block d-md-none text-wrap">
            <h4 style={{ fontSize: '50px', lineHeight: '68px', fontWeight: '500' }} className='text-center text-break'>My&nbsp;
              <Image src={Book} width={52} height={60} alt="Picture of the author" />
              <Link href="#" className="text-black">CRM</Link>,
              <Image src={Paper} width={52} height={60} alt="Picture of the author" />
              <Link href="#" className="text-black">HR,</Link><br />&
              <Image src={Point} width={52} height={60} alt="Picture of the author" />
              <Link href="#" className="text-black">projects.</Link>Together.
            </h4>
          </div>
          {/* display only above md */}
          <div className="col-12 d-none d-md-block">
            <h1 style={{ fontSize: '76.5px', lineHeight: '78px', fontWeight: '700' }} className='text-center text-break'>My&nbsp;
              <Image src={Book} width={52} height={60} alt="Picture of the author" />
              <Link href="#" className="text-black">CRM</Link>,
              <Image src={Paper} width={52} height={60} alt="Picture of the author" />
              <Link href="#" className="text-black">HR,</Link><br />&
              <Image src={Point} width={52} height={60} alt="Picture of the author" />
              <Link href="#" className="text-black">PM</Link>Together.
            </h1>
          </div>
          <div className='text-center'>
            <h4 className='a-bol' style={{ fontSize: "24px", lineHeight: '30px' }}>Stubsuite is startup to unicorn business suite. <br /> better, faster work happens. Now with AI </h4>
            <button type="button" className="btn btn-dark fw-medium mt-2 mb-3">Get your business 2x with stubsuite</button> <br />
            <Image src={HomeHero} className='mw-100' height={260} alt="Logo" />
          </div>
        </div>
        <div className="row">
          <div className="offset-sm-1 col-sm-11 offset-sm-1 col-12">
            {/* <div style={{ boxShadow: 'rgba(0, 0, 0, 0.05) 0px 1px 2px 0px' }}>
              <div style={{ position: 'relative', top: "4rem", left: '64px' }}>
                <Image src={Mobile} className='d-none d-xl-block' style={{ right: '0px', position: 'absolute', width: '27%', height: "auto", top: '152%' }} alt="Logo" />
              </div>
            </div> */}
            <div className='col-12'>
              <ServicesV1 />
              {/* <Image src={Desktop} className='w-100 h-75' style={{ boxShadow: 'rgba(100, 100, 111, 0.2) 0px 7px 29px 0px' }} alt="Logo" /> */}
            </div>
          </div>
        </div>
        <div className="row my-5">
          <div className='text-center'>
            <h1 className='h1Custom mt-5' style={{ fontSize: "45px", lineHeight: '49px' }}>Millions run on Notion every day</h1>
            <p style={{ fontWeight: "400" }}>Powering the world’s best teams, from next-generation startups <br /> to established enterprises.</p>
            <Link href="#" style={{ color: "#0a85d1", fontWeight: '400' }}>Read customer stories</Link> <br />
            <Image src={Combine} className='w-75 h-auto' alt="Logo" />
          </div>
        </div>
        <div className="row mb-4">
          <div className="text-center">
            <h1>Finally, all your work <br /> in one place</h1>
          </div>
        </div>
      </div>
      <div className="row mx-0 d-flex justify-content-between">
        <div className="col-lg-3 offset-lg-1 col-12">
          <div style={{ paddingLeft: '38px', paddingRight: "42px", height: '45%' }}>
            <h5> <b>Wikis</b></h5>
            <h6>It’s hard to move fast if you can’t find anything. Centralize all your knowledge in Notion.</h6>
            <Link href="#" className='text-decoration-none' style={{ color: "#996600" }}>Explore</Link> <br />
          </div>
          <Image src={Girl} className='w-75 d-none d-lg-block ms-auto my-auto' height={320} alt="Logo" />
        </div>
        <div className="col-lg-8 col-12 p-0">
          <Image style={{ boxShadow: "rgba(149, 157, 165, 0.2) 0px 8px 24px" }} src={GirlSide} className='mw-100 rounded-start-4 h-auto' alt="Logo" />
        </div>
      </div>
      <div className="row mx-0 my-5 d-flex justify-content-between">
        <div className="col-lg-3 offset-lg-1 col-12">
          <div style={{ paddingLeft: '38px', paddingRight: "42px", height: '45%' }}>
            <h5> <b>Docs</b></h5>
            <h6>Simple. Powerful. Beautiful. Communicate more efficiently with next generation docs.</h6>
            <Link href="#" className='text-decoration-none' style={{ color: "#996600" }}>Explore</Link> <br />
          </div>
          <Image src={DocsIllo} className='w-75 d-none d-lg-block ms-auto my-auto' height={320} alt="Logo" />
        </div>
        <div className="col-lg-8 col-12 p-0">
          <Image style={{ boxShadow: "rgba(149, 157, 165, 0.2) 0px 8px 24px" }} src={MeetingNotes} className='mw-100 rounded-start-4 h-auto' alt="Logo" />
        </div>
      </div>
      <div className="row mx-0 d-flex justify-content-between">
        <div className="col-lg-3 offset-lg-1 col-12">
          <div style={{ paddingLeft: '38px', paddingRight: "42px", height: '45%' }}>
            <h5> <b>Projects</b></h5>
            <h6>Manage any type of project more efficiently. No separate, clunky system.</h6>
            <Link href="#" className='text-decoration-none' style={{ color: "#996600" }}>Explore</Link> <br />
          </div>
          <Image src={ProjectsIllo} className='w-75 d-none d-lg-block ms-auto my-auto' height={320} alt="Logo" />
        </div>
        <div className="col-lg-8 col-12 p-0">
          <Image style={{ boxShadow: "rgba(149, 157, 165, 0.2) 0px 8px 24px" }} src={Projects} className='mw-100 rounded-start-4 h-auto' alt="Logo" />
        </div>
      </div>
      <div className="row mx-0 mt-5 d-flex justify-content-between">
        <div className="col-lg-3 offset-lg-1 col-12">
          <div style={{ paddingLeft: '38px', paddingRight: "42px", height: '45%' }}>
            <h5> <b>Notion AI</b></h5>
            <h6>Access the limitless power of AI, right inside Notion.</h6>
            <Link href="#" className='text-decoration-none' style={{ color: "#996600" }}>Explore</Link> <br />
          </div>
          <Image src={AiIlloV5} className='w-75 d-none d-lg-block ms-auto my-auto' height={320} alt="Logo" />
        </div>
        <div className="col-lg-8 col-12 p-0">
          <Image style={{ boxShadow: "rgba(149, 157, 165, 0.2) 0px 8px 24px" }} src={AiV5} className='mw-100 rounded-start-4 h-auto' alt="Logo" />
        </div>
      </div>
      <div className="container mt-5">
        <div className="row">
          <div className="text-center">
            <div className="row">
              <h1 className='offset-sm-4 col-sm-4 col-12 fontSans'>Consolidate tools. <br />Cut costs.</h1>
              <div className="col-2 d-none d-sm-block p-0">
                <Image src={GiantPencil} style={{ position: 'relative', bottom: '-12px', width: '100%' }} height={183} alt="Logo" />
              </div>
            </div>
            <div className='d-none d-sm-block' style={{ position: 'relative', right: '26%', top: '9px' }}>
              <Image src={ToolsStrikethrough} style={{ mixBlendMode: 'multiply', position: 'absolute', height: 'auto', width: '53%' }} alt="Logo" />
            </div>
            <Image src={ToolsBeforeNotion} style={{ width: '50%', height: 'auto' }} alt="Logo" />
            <blockquote><h3 className='fontSerif'>“We got rid of nearly a dozen different tools because of <br /> what Notion does for us.”</h3></blockquote>
            <div className="d-flex justify-content-center">
              <Image src={Metalab} className='me-2' width={100} height={50} alt="Logo" />
              <div className='text-start'>
                <b>Justin Watt</b><p>Director of Ops & Marketing, MetaLab</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="container">
        <div className="row">
          <div className="col-10 offset-1">
            <h1 className='col-12 d-lg-none'>Powerful building blocks</h1> <br />
            <div className="d-flex align-items-center">
              <div className="col-3">
                <Image src={TopPeekI} style={{ height: 'auto', width: '85vmin', boxSizing: 'border-box', position: 'relative', top: '17px' }} alt="Logo" />
              </div>
              <div className="col-8 offset-3">
                <h1 className='mb-0 mt-4 d-none d-lg-block'>Powerful building blocks</h1>
              </div>
            </div>
          </div>
        </div>
        <div className="row">
          <div className="col-12">
            <div className="rounded-3 px-5" style={{ backgroundColor: '#F6F5F4' }}>
              <div className="col-sm-8 col-12">
                <h4 className='p-3 mb-0'>Visualize, filter & sort any way you want</h4>
                <p className='p-3 mb-0 fw-bold'>Show only tasks assigned to you, or items marked as urgent. Break down any project in the way that’s most helpful to you.</p>
              </div>
              <LowerCarosal />
            </div>
          </div>
        </div>
      </div>
      <div className="container mt-3">
        <div className="row">
          <div className="col-sm-6 col-12">
            <div className="rounded-3" style={{ backgroundColor: '#F6F5F4' }}>
              <div className='p-5'>
                <h4>Customize the info you track</h4>
                <p className='mb-0'>Create your own labels, tags, owners, and more, so everyone has context and everything stays.</p>
              </div>
              <div className='d-flex justify-content-end me-1'>
                <Image src={CustomizeInfo} className='w-75 h-auto' alt="Logo" />
              </div>
            </div>
          </div>
          <div className="col-sm-6 col-12 mt-2 mt-sm-0">
            <div className="rounded-3" style={{ backgroundColor: '#F6F5F4' }}>
              <div className='p-5'>
                <h4>Build any page, communicate any idea</h4>
                <p className='mb-0'>Everything is drag and drop in Notion — images, toggles, to-do’s, even embedded databases.</p>
              </div>
              <div className='d-flex justify-content-end me-1'>
                <Image src={buildAnyPageCommunicateAnyIdea} className='w-75 h-auto' alt="Logo" />
              </div>

            </div>
          </div>
        </div>
        <div className="row">
          <div className="text-center my-5">
            <blockquote><h3 className='fontSerif mt-5'>“Notion adapts to your needs. It’s as minimal or as <br /> powerful as you need it to be.”</h3></blockquote>
            <div className="d-flex justify-content-center">
              <Image src={Metalab} className='me-2' width={100} height={50} alt="Logo" />
              <div className='text-start'>
                <b>Justin Watt</b><p>Director of Ops & Marketing, MetaLab</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <UpperCarosal />
      <div className="container">
        <div className="row">
          <div className="text-center mt-5">
            <p className="fs-1 fw-bolder">Join a global movement. <br /> Unleash your creativity.</p>
            <p className="fw-medium">Our vibrant community produces content, teaches courses, and leads events all over <br /> the world.</p>
            <Link href="#" className='text-decoration-none'>Learn more</Link> <br />
            <Image src={Avatars} className='me-2 mw-100' height={150} alt="Logo" />
          </div>
        </div>
      </div>
      <div className="container">
        <div className="row my-5">
          <div className='d-block d-md-none'>
            <div className="d-flex justify-content-around">
              <div className="col-sm-3 col-4 mt-1 rounded-3 ps-3" style={{ backgroundColor: '#F6F5F4' }}>
                <h5 className='text-primary'>1M+</h5>
                <p className='fw-medium'>community members</p>
              </div>
              <div className="col-sm-3 col-4 mt-1 mx-1 rounded-3 ps-3" style={{ backgroundColor: '#F6F5F4' }}>
                <h5 className='text-primary'>1M+</h5>
                <p className='fw-medium'>community members</p>
              </div>
              <div className="col-sm-3 col-4 mt-1 rounded-3 ps-3" style={{ backgroundColor: '#F6F5F4' }}>
                <h5 className='text-primary'>1M+</h5>
                <p className='fw-medium'>community members</p>
              </div>
            </div>
          </div>
          <div className='d-none d-md-block'>
            <div className="d-flex justify-content-between">
              <div className="col-sm-3 col-4 rounded-3 px-5" style={{ backgroundColor: '#F6F5F4' }}>
                <h1 className='text-primary my-3 ps-2'>1M+</h1>
                <p className='fw-medium'>community members</p>
              </div>
              <div className="col-sm-3 col-4 rounded-3 px-5" style={{ backgroundColor: '#F6F5F4' }}>
                <h1 className='text-primary my-3 ps-2'>1M+</h1>
                <p className='fw-medium'>community members</p>
              </div>
              <div className="col-sm-3 col-4 rounded-3 px-5" style={{ backgroundColor: '#F6F5F4' }}>
                <h1 className='text-primary my-3 ps-2'>1M+</h1>
                <p className='fw-medium'>community members</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="container">
        <div className="row">
          <div className="d-sm-flex justify-content-sm-between">
            <div className="col-sm-6 col-12 rounded-3  px-3 pt-4" style={{ backgroundColor: '#F6F5F4' }}>
              <h5 className='my-3 my-3 fw-bold'>An always-on support network</h5>
              <p className='fw-medium pb-5'>Swap setups and share tips in over 149 online communities.</p>
              <Image src={CommunityIcons} className='me-2 mw-100 h-50' alt="Logo" />
            </div>
            <div className="col-sm-6 ms-1 col-12 rounded-3 px-3 pt-4 mt-2 mt-sm-0" style={{ backgroundColor: '#F6F5F4' }}>
              <div className='d-flex align-items-end flex-column'>
                <div className="p-2">
                  <h5 className='my-3 my-3 fw-bold'>An always-on support network</h5>
                  <p className='fw-medium pb-5'>Swap setups and share tips in over 149 online communities.</p>
                </div>
                <div className="" style={{ marginTop: '37%' }}>
                  <Image src={WelcomeToNotion} className='ps-5 mw-100 h-50' alt="Logo" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="container">
        <div className="ro mt-5">
          <div className="d-sm-flex justify-content-sm-between">
            <div className="row">
              <SimpleCarosal />
              <div className="col-lg-4 px-3 mt-2 mt-lg-0" >
                <div className="row">
                  <div className='mx-md- rounded-4' style={{ backgroundColor: '#F6F5F4' }}>
                    <div className='d-flex align-items-end flex-column'>
                      <div className="p-3">
                        <div className='d-flex align-items-center pb-3'>
                          <Image src={TwitterAvatarDeborah} style={{ width: '15%', height: 'fit-content' }} alt="Logo" />
                          <p className='mb-0 ps-1'> <b>Deborah Mecca </b> <br />@DebMecca</p>
                        </div>
                        <p className='fw-medium'>I used to HATE documenting things. And then I started using @NotionHQ and I document a lot. A LOT A LOT. Now I just realize that it wasn't that I hated documenting, I just hated Google Docs.</p>
                      </div>
                    </div>
                  </div>
                  <div className='mx-md- rounded-4 my-1' style={{ backgroundColor: '#F6F5F4' }}>
                    <div className='d-flex align-items-end flex-column'>
                      <div className="p-3">
                        <div className='d-flex align-items-center pb-3'>
                          <Image src={TwitterAvatarDeborah} style={{ width: '15%', height: 'fit-content' }} alt="Logo" />
                          <p className='mb-0 ps-1'> <b>Deborah Mecca </b> <br />@DebMecca</p>
                        </div>
                        <p className='fw-medium'>I used to HATE documenting things. And then I started using @NotionHQ and I document a lot. A LOT A LOT. Now I just realize that it wasn't that I hated documenting, I just hated Google Docs.</p>
                      </div>
                    </div>
                  </div>
                  <div className='ms-md- rounded-4' style={{ backgroundColor: '#F6F5F4' }}>
                    <div className='d-flex align-items-end flex-column'>
                      <div className="p-3">
                        <div className='d-flex align-items-center pb-3'>
                          <Image src={TwitterAvatarDeborah} style={{ width: '15%', height: 'fit-content' }} alt="Logo" />
                          <p className='mb-0 ps-1'> <b>Deborah Mecca </b> <br />@DebMecca</p>
                        </div>
                        <p className='fw-medium'>I used to HATE documenting things. And then I started using @NotionHQ and I document a lot. A LOT A LOT. Now I just realize that it wasn't that I hated documenting, I just hated Google Docs.</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="container">
        <div className="row">
          <h1 className='text-center mt-5'>Endless ways to use it</h1>
          <div className="col-lg-6 col-12 rounded-3 py-2" style={{ backgroundColor: '#F1EFEE' }}>
            <h5 className='ps-3 pt-3'>Company Wiki</h5>
            <div className='d-flex align-items-end flex-column' >
              <Image src={CompanyWikiTemplate} className='rounded-3 border w-75  h-100 mt-2' alt="Logo" />
            </div>
          </div>
          <div className="col-lg-6 col-12 mt-1">
            <div className="row">
              <div className="col-sm-6 ps-0 ps-lg-3">
                <div className='rounded-3 p-4' style={{ backgroundColor: '#F1EFEE' }}>
                  <h6>Product roadMap</h6>
                  <Link href='#' className='text-primary nav-link'>Get Template</Link>
                </div>
                <div className='rounded-3 p-4 my-5' style={{ backgroundColor: '#F1EFEE' }}>
                  <h6>Metting Notes</h6>
                  <Link href='#' className='text-primary nav-link'>Get Template</Link>
                </div>
                <div className='rounded-3 p-4' style={{ backgroundColor: '#F1EFEE' }}>
                  <h6>Editorial calendar</h6>
                  <Link href='#' className='text-primary nav-link'>Get Template</Link>
                </div>
              </div>
              <div className="col-sm-6 d-none d-sm-block ps-0 ps-lg-3">
                <div className='rounded-3 p-4' style={{ backgroundColor: '#F1EFEE' }}>
                  <h6>OKRs</h6>
                  <Link href='#' className='text-primary nav-link'>Get Template</Link>
                </div>
                <div className='rounded-3 p-4 my-5' style={{ backgroundColor: '#F1EFEE' }}>
                  <h6>Vacation planner</h6>
                  <Link href='#' className='text-primary nav-link'>Get Template</Link>
                </div>
                <div className='rounded-3 p-4' style={{ backgroundColor: '#F1EFEE' }}>
                  <h6>Habit tracker</h6>
                  <Link href='#' className='text-primary nav-link'>Get Template</Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="container">
        <div className="row">
          <div className="text-center mt-5">
            <p className="fs-1 fw-bolder">Get started for free</p>
            <p className="fw-medium">Play around with it first. Pay and add your team later.</p>
            <button type="button" className="btn btn-dark fw-medium me-3">Get Notion free</button>
            <Link href="#" className='text-decoration-none'>Request a demo</Link> <br />
            <Image src={NotionParade} className='mw-100' width={700} height={400} alt="Logo" />
          </div>
        </div>
      </div>
      <div className="container-fluid">
        <hr className='m-0' />
      </div>
      <div className="container">
        <div className="row my-5">
          <div className="col-3">
            <Link className="navbar-brand col-1" href="#"><Image src={NotionLogo} width={30} height={30} alt="Logo" /> Notion</Link>
          </div>
          <div className="col-3">
            <p>EXPLORE CRM</p>
            <p>CRM Essentials</p>
            <p>CRM Essentials</p>
            <p>CRM Essentials</p>
            <p>CRM Essentials</p>
            <p>CRM Essentials</p>
            <p>CRM Essentials</p>
          </div>
          <div className="col-3">
            <p>EXPLORE CRM</p>
            <p>CRM Essentials</p>
            <p>CRM Essentials</p>
            <p>CRM Essentials</p>
            <p>CRM Essentials</p>
            <p>CRM Essentials</p>
            <p>CRM Essentials</p>
          </div>
          <div className="col-3">
            <p>EXPLORE CRM</p>
            <p>CRM Essentials</p>
            <p>CRM Essentials</p>
            <p>CRM Essentials</p>
            <p>CRM Essentials</p>
            <p>CRM Essentials</p>
            <p>CRM Essentials</p>
          </div>
        </div>
      </div>
    </>
  )
}
